# Server properties
server:
  error:
    include-stacktrace: always  # When to include a "stacktrace" attribute.
    path: /error # Path of the error controllers.
    whitelabel.enabled: true # Enable the default error page displayed in browsers in case of a server error.

# Logging
logging:
  config: classpath:config/logback/development.xml
#  level:
#    org:
#      springframework:
#        web:  DEBUG
#        core: INFO
#      hibernate: DEBUG